services:
  php-fpm:
    build: 
      context: ./dev
      dockerfile: Dockerfile.dev.php-fpm
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    networks:
      - digistock-dev-network
      - digistock-dev-cache-network
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - digistock-dev-php-fpm-project:/var/www/html
    depends_on:
      - db
        
  nginx:
    build: 
      context: ./dev
      dockerfile: Dockerfile.dev.nginx
    ports:
      - "80:80"
    volumes:
      - ./dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dev/nginx/logs/:/var/log/nginx/
      - digistock-dev-php-fpm-project-public:/var/www/html/public
    networks:
      - digistock-dev-network
    depends_on:
      - php-fpm
  
  redis:
    build:
      context: ./dev
      dockerfile: Dockerfile.dev.redis
    ports:
      - "6379:6379"
    networks:
      - digistock-dev-cache-network
    depends_on:
      - php-fpm

  workspace:
    build:
      context: ./dev
      dockerfile: Dockerfile.dev.workspace
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes: 
      - digistock-dev-php-fpm-project:/var/www/html
    networks:
      - digistock-dev-network
      - digistock-dev-cache-network
    tty: true
    env_file:
      - ./dev/workspace/.env.db
  
  db:
    build:
      context: ./dev
      dockerfile: Dockerfile.dev.db
    ports:
      - "3306:3306"
    volumes:  
      - digistock-dev-db:/var/lib/mysql
      - ./dev/db/scripts/:/docker-entrypoint-initdb.d/
    networks:
      - digistock-dev-network
    env_file:
      - ./dev/db/.env.db
  
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - digistock-dev-cache-network
    volumes:
      - digistock-dev-redis-insight-data:/data
    depends_on:
      - redis
    
volumes:
  digistock-dev-php-fpm-project:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev/php-fpm/project/

  digistock-dev-php-fpm-project-public:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev/php-fpm/project/public/

  digistock-dev-db:

  digistock-dev-redis-insight-data:

networks:
  digistock-dev-network:
    driver: bridge
  digistock-dev-cache-network:
    driver: bridge